---
title: "lasso_regression_model_3"
output: html_document
---

```{r}
library(tidyverse)
library(glmnet)
library(glmnetUtils)
library(kableExtra)
```

```{r}
##import data and util functions
gun_train = read.csv("../data/training.csv") %>% select(-c(X))
gun_test = read.csv("../data/test.csv") %>% select(-c(X))
source("util_functions.R")
```

```{r}
##fit ridge regression model with 10 cv folds
set.seed(5)
lasso_fit = cv.glmnet(log_incident_rate ~ ., alpha = 1, nfolds = 10, data = gun_train)
```

```{r}
##plot cv plot
plot(lasso_fit)
```

```{r}
lambda = lasso_fit$lambda.1se
sprintf("The value of lambda based on the one-standard-error rule: %f",
        lambda)
```

```{r}
##get non zero coeffs
extract_std_coefs(lasso_fit, gun_train) %>% 
  filter(coefficient != 0)
  
```


```{r}
#plot features
plot_glmnet(lasso_fit, gun_train, features_to_plot = 6)
```

```{r} 
## Lasso RMSE is 0.8317696
lasso_predictions = predict(lasso_fit, 
                            newdata = gun_test, 
                            s = "lambda.1se")
lasso_RMSE = sqrt(mean((lasso_predictions - gun_test$log_incident_rate)^2))
lasso_RMSE
```


